### PR TITLE
Add Material-like mono SVG icon, and map others.

### PR DESCRIPTION
**Pull request by CDrummond**
For Material 2.3.0 I've added support for loading plugin provided SVG icons. If an icon ends with ".svg.png" then MaterialSkin will try to load ".svg" from the plugins folder. e.g. When LMS lists `plugins/VirginRadio/html/images/VirginRadioLogo.svg.png` Material will look for `plugins/VirginRadio/html/images/VirginRadioLogo.svg` This allows a plugin to provide its own SVG, and means Material does not need to update its mapping file for each plugin. I'm open to using a different mapping (i.e. the ".svg.png" to ".svg" mapping) but wanted something generic.

To this end I've created `VirginRadioLogo.svg.png` from your `VirginRadio.png` - as this PNG is used as both the plugin logo and for one of the stations. In Material I'd like to use the SVG for the plugin logo, but still used the PNG for the station.

I've also mapped `radio` as the icon to be used for the "Live Virgin Radio Stations" category. Mixing icons and images in the first level looked odd to me.

-------------------

As an aside, Material ships with an SVG icon for your Times radio plugin. If this pull request is accepted, shall I make a similar change there?

### CODE REVIEW

**Comment by expectingtofly** [comment]
Fine by me.
I have a couple of questions  : 

1. Is your change in Material for all image/icons including menu/links or just for plugin/app icons?   If its for menu items as well,  there may already be a solution for a plugin to supply alternative images to a controller (there is an "image" and an "icon" property on "link" type menu items, Default skin ignores the "icon" property, Material skin can use either, I notice)

2. Does the double extensions cause any problems an any of the operating systems file systems?

**Comment by expectingtofly** [comment]
> As an aside, Material ships with an SVG icon for your Times radio plugin. If this pull request is accepted, shall I make a similar change there?

No worries, I'll make the change, I have a couple of other changes to do to that plugin.

**Comment by CDrummond** [comment]
The code applies to all ".svg.png" images. I was not sure wht the different icon typed were (icon, icon-id, image, etc)!

As to the extension causing trouble, I don't see why it should - but I'm 100% Linux so have not tested on others, but would be pretty silly if it caused issues. I can change it to "_svg.png", or indeed anything else, if it helps?

As for TimesRadio - you can take the Material icon if you like: https://raw.githubusercontent.com/CDrummond/lms-material/master/MaterialSkin/HTML/material/html/images/times-radio.svg

**Comment by CDrummond** [comment]
...also likewise for the BBC Sounds plugin: https://raw.githubusercontent.com/CDrummond/lms-material/master/MaterialSkin/HTML/material/html/images/bbc-sounds.svg

If you do update your 3 plugins, I'll remove the mapping from Material for 2.3.0

**Comment by expectingtofly** [comment]
> The code applies to all ".svg.png" images. I was not sure wht the different icon typed were (icon, icon-id, image, etc)!

Yes, I found it confusing, I was just using icon, then I noticed default skin ignored it! (all other controllers don't, but I don't know what the order of precedence is on other controllers, so it probably can't be used as an alternative.)

> As to the extension causing trouble, I don't see why it should - but I'm 100% Linux so have not tested on others, but would be pretty silly if it caused issues. I can change it to "_svg.png", or indeed anything else, if it helps?

Yes, it was Windows I was worried about, it can be silly!  I don't have a way of testing that either, but you are probably right, it should be fine.  
Ok, shall we just go with it as is, its easy enough to change if it causes Windows Server users a problem, I'll merge it in.

**Comment by expectingtofly** [comment]
> ...also likewise for the BBC Sounds plugin: https://raw.githubusercontent.com/CDrummond/lms-material/master/MaterialSkin/HTML/material/html/images/bbc-sounds.svg
> 
> If you do update your 3 plugins, I'll remove the mapping from Material for 2.3.0

Thanks

**Pull request merged**
